name: Deploy-to-EC2

on:
  push:
    branches:
      - CAR-166-ci-deployment

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install package
        run: sudo npm install -g @expo/ngrok@^4.1.0

      - name: Expo start
        run: npm run start
                